### ISSUE TITLE
build and upload docker images from travis

### ISSUE THREAD

**Issue by shanmukhananda** [paul-michalik/ORB_SLAM2#16]
Travis should build and upload new docker image if dockerfile or bootstrap.sh is changed

**Comment by shanmukhananda** [comment]
Ubuntu 17.10 provides OpenCV-3.1.0 as part of apt-get install. Can we switch to this, instead of building opencv from source? Docker image for ORB-SLAM2 is already build from ubuntu:17.10 base.
```
libopencv-dev/artful 3.1.0+dfsg1-1~exp1ubuntu3 amd64
  development files for opencv
```

**Comment by paul-michalik** [comment]
Yes, prefer apt-get! Otherwise I would not put too much logic into checking for modifications in dockerfile or bootstrap.sh. This should stay straightforward and be explicitly invokable by the user...

**Comment by shanmukhananda** [comment]
Tested working with apt-get's opencv. 

Checking the modifications in dockerfile and bootstrap.sh is added because, I want an automated setup where docker images are provisioned and uploaded to docker hub. 

Hence whenever a change is made inside dockerfile and bootstrap.sh new image is built and uploaded to [docker registry](https://hub.docker.com/r/shanmukhananda/orb-slam2). Further builds from travis or from user refers updated docker image.

**Comment by paul-michalik** [comment]
Yes, that is obvious. As mentioned in the comment, I would prefer a warning message or maybe even a failure of the build process instead of automatically building and uploading the Docker image. That should operation should be explicitly issued by the user.

**Comment by shanmukhananda** [comment]
Detailed description of the changes

```
On each commit on every branch
    IF "Dockerfile" is changed OR "bootstrap.sh" is changed
        docker-build a new image with tags "orb-slam2:latest", "orb-slam2:build-number"
    
    build orb-slam2 using docker image "orb-slam2:latest"
        // "orb-slam2:latest" image is used if present locally else its pulled from docker hub
    
    IF docker-build is successful AND orb-slam2 build is successful
        IF current travis build is on "master" AND current travis build is not due to pull request        
            login to docker hub
            upload docker images "orb-slam2:latest", "orb-slam2:build-number"
```

**Why two tags are used for docker images?**

"orb-slam2:latest" and "orb-slam2:build-number" tags are used to build and upload docker images
This is to maintain the history for tractability and ability to use older docker images. 

If we use only one tag "orb-slam2:latest" on each docker push this image is overwritten.

![docker-workflow](https://user-images.githubusercontent.com/6041150/33429940-a5e3bbf2-d5f4-11e7-8f62-0b307ea915d6.jpg)
