### ISSUE TITLE
Boxes for semantic features are obviously wrong

### ISSUE THREAD

**Issue by paul-michalik** [paul-michalik/ORB_SLAM2#32]
At least the visualization of semantic features in the drawer is obviously not correct. Please verify with original data and propose a fix.
![capture](https://user-images.githubusercontent.com/10583150/33675243-364f801a-dab2-11e7-8e87-6d34fffad855.JPG)

**Comment by paul-michalik** [comment]
Turns out this is a synchronization/data race issue. There is a data exchange between tracking and viewer threads synchronized via explicit locking in `FrameDrawer::Update` and `FrameDrawer::DrawFrame`: 

![capture](https://user-images.githubusercontent.com/10583150/33720884-a1fa2af0-db65-11e7-85cd-43143c91283e.JPG)

In `FrameDrawer::Update` we need to retrieve all information related to current frame, such as: image, frame ID, current keypoints, etc. The information is stored in member variables of `FrameDrawer` and accessed in `FrameDrawer::DrawFrame` form the viewer thread. In order to prevent data races which result in "torn" frames it is essential that all access to the frame related data happens inside the scope protected by `FrameDrawer::mMutex`. This means that all data regarding the frame information needs to be fetched into stack variables inside the protected scope:

```
cv::Mat FrameDrawer::DrawFrame()
{
    //...
    //Copy variables within scoped mutex
    {
        unique_lock<mutex> lock(mMutex);
        // ...     
    }
```
Do not access any other data (member variables or global) inside `FrameDrawer::DrawFrame`!

**Comment by apattnaik0721013** [comment]
1. Added std::vector<cv::Rect> mRoiList to frame which hold semantic rectangle for that frame.
2. this mRoiList is used to draw semantic rectangle.
3. remove semantic frame information as it is handled in separate issue.
