### ISSUE TITLE
Add PVR functions to the application

### ISSUE THREAD

**Issue by paul-michalik** [paul-michalik/ORB_SLAM2#39]
Please implement following user stories:
 
1. As a user I want to postpone the start of the application until a "play" button is pushed if the application is started in GUI mode
2. As a user I want to pause the execution of the application and manipulate (zoom in and out, move around) the map view
3. As a user I want to resume the execution of the application from a previously paused state

This boils down to implementing PVR-like UI commands which control a state machine as shown in the picture. A headless mode should still be supported in this case there is only "PLAYING" state which is entered automatically from the start state, is kept active until images are available and is left to termination state when finished or when an error occurred. Certain actions should only be available from "STOPPED" state such as saving a map, loading a map or resetting the map. 

Please note that (2) means that we need to stop the tracking  thread and not the view thread. Basically, no new images might be pushed into the pipeline while in "PAUSED" or "STOPPED" states. 

![capture](https://user-images.githubusercontent.com/10583150/33842010-9d6280d2-de99-11e7-96e9-6a77bb33f9f2.JPG)

**Comment by apattnaik0721013** [comment]
@paul-michalik 
I didnt understand the difference between paused and stopped stated.
Can you clarify between these two in terms of the action to be performed.

**Comment by paul-michalik** [comment]
Implemented and submitted.
