### ISSUE TITLE
script fix to build faster in linux

### ISSUE THREAD

**Issue by shanmukhananda** [paul-michalik/ORB_SLAM2#5]
The current implementation of build_linux.sh is very slow in linux because we are bootstrapping and extracting vocabulary everytime, this kind of implementation is time consuming if we are changing the source frequently.

**Comment by paul-michalik** [comment]
Ok, that's true. But you know that you don't have run this script every time? Run it once to set up the environment and then use the generated makefiles or ninja files when editing. On `make <target>` CMake generator will rerun automatically whenever appropriate. Nevertheless we could separate bootstrapping from build script generation but then this should be coherent for all platforms.

**Comment by shanmukhananda** [comment]
same changes are required for issue-8-add travis-ci support too, hence closing this issue.
