### ISSUE TITLE
macs-style-project-structure

### ISSUE THREAD

**Issue by shanmukhananda** [paul-michalik/ORB_SLAM2#50]
Current Problems

P: Chaotic CMakeLists.txt
S: Divide and conquer like in macs 

P: Chaotic Readme
S: Divide and conquer like in macs 

P: New source files lies with existing ones
S: Move new source files to 'ext' folder like with app_monitor

P: Folder naming is not following any standard
S: Follow macs folder structures

P: Cotire Support
S: Added Cotire support by using git-submodules as in macs

P: Support for precompilation
S: Added precompile.h to support precompilation. (currently default cotire prefix header and unity builds are used, as the build times are better with defaults)

P: Different code formatting
S: Use clang-format to standardize the code format.
Benefits:
	- Few functions like Frame ctor is painfully hard to read with lot of parameters becomes legible after clang-format
	- Different users using different style, IDE settings, clang-format hides all these and brings the code to a common format
	- Large scale projects like Qt uses this. Many c++ developers in conferences insists on using clang-format
	- After clang-format code becomes easy to use with merge/diff tools during rebase and merge processes

P: Bug: System class constructor is added with app_monitor parameter leading to compilation failure of few examples
S: Moved new parameter to end of parameter list in System ctor.

P: Examples are OFF during building
S: All the examples are turned ON, this way users can know if code change is causing any compilation error in any of the examples. Developers should selectively configure this locally to save build time.

P: Bootstrapping deletes the apt-get cache
S:  apt-cache is delete only for docker images

P: apt-get installs so many unnecessary stuffs
S:  refactor apt-get items

**Comment by paul-michalik** [comment]
@shanmukhananda These are all serious problems but they are not ours! ;-) We can't change the structure of a third party project in a way which renders it incompatible to the original. For now, please restrict the changes and additions to the `ext` folder. If the structure of this project does not fit anymore, we need to switch to macs project which **uses** ORB-SLAM2 as a dependency. This is required anyway so better we start now.

**Comment by shanmukhananda** [comment]
Agreed. Moving the new files to ext folder will be handled in new issue.

I'm keeping the related branch alive as its kind of comfortable environment for me to read and understand.
