### ISSUE TITLE
CMake Error: install(EXPORT "orb-slam2Config" ...) includes target "orb-slam2" which requires target "DBoW2" that is not in the export set.

### ISSUE THREAD

**Issue by arnwik** [paul-michalik/ORB_SLAM2#52]
I have followed the tutorial but in the "end" I get this error. Any clue on what I have missed?
Here is the complete output:
C:\Users\XYZ\Documents\ORB_SLAM2>call scripts/windows/build.bat x64 v141 Release
vcpkg found at C:\Users\XYZ\.vcpkg\vcpkg...

Bootstrapping dependencies for triplet: x64-windows-v141

Using local portfile versions. To update the local portfiles, use `git pull`.
No packages need updating.
There are no outdated packages.
The following packages are already installed:
    boost:x64-windows-v141
    eigen3:x64-windows-v141
    opencv:x64-windows-v141
    pangolin:x64-windows-v141
Starting package 1/4: boost:x64-windows-v141
Package boost:x64-windows-v141 is already installed
Elapsed time for package boost:x64-windows-v141: 888.4 us
Starting package 2/4: eigen3:x64-windows-v141
Package eigen3:x64-windows-v141 is already installed
Elapsed time for package eigen3:x64-windows-v141: 603.8 us
Starting package 3/4: opencv:x64-windows-v141
Package opencv:x64-windows-v141 is already installed
Elapsed time for package opencv:x64-windows-v141: 604.5 us
Starting package 4/4: pangolin:x64-windows-v141
Package pangolin:x64-windows-v141 is already installed
Elapsed time for package pangolin:x64-windows-v141: 447.1 us

Total elapsed time: 3.647 ms

The package boost is compatible with built-in CMake targets:

    find_package(Boost REQUIRED [COMPONENTS <libs>...])
    target_link_libraries(main PRIVATE ${Boost_LIBRARIES})
    target_include_directories(main PRIVATE ${Boost_INCLUDE_DIRS})

The package eigen3:x64-windows-v141 provides CMake targets:

    find_package(eigen3 REQUIRED)
    target_link_libraries(main PRIVATE Eigen3::Eigen)

The package opencv:x64-windows-v141 provides CMake targets:

    find_package(lib REQUIRED)
    # Note: 40 targets were omitted
    target_link_libraries(main PRIVATE ${__cvcomponent} opencv_core opencv_flann opencv_imgproc)

The package pangolin:x64-windows-v141 provides CMake targets:

    find_package(pangolin REQUIRED)
    target_link_libraries(main PRIVATE pangolin)

Bootstrapping successful for triplet: x64-windows-v141
CMAKE_PREFIX_PATH=C:\Users\XYZ\.vcpkg\vcpkg\installed\x64-windows-v141;

-- OpenCV ARCH: x64
-- OpenCV RUNTIME: vc15
-- OpenCV STATIC: ON
-- Found OpenCV 3.3.1 in C:/Users/XYZ/.vcpkg/vcpkg/installed/x64-windows-v141/share/opencv/x64/vc15/lib
-- You might need to add C:\Users\XYZ\.vcpkg\vcpkg\installed\x64-windows-v141\share\opencv\x64\vc15\bin to your PATH to be able to run your applications.
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   filesystem
--   system
-- BUILD TYPE:Release
-- Configuring done
CMake Error: install(EXPORT "orb-slam2Config" ...) includes target "orb-slam2" which requires target "DBoW2" that is not in the export set.
CMake Error: install(EXPORT "orb-slam2Config" ...) includes target "orb-slam2" which requires target "g2o" that is not in the export set.
-- Generating done
-- Build files have been written to: C:/Users/XYZ/Documents/ORB_SLAM2/products/cmake.msbuild.windows.x64.v141
configure error, bailing out

C:\Users\XYZ\Documents\ORB_SLAM2>cd ORB_SLAM2

**Comment by paul-michalik** [comment]
Look like `install` commands are broken on master! @apattnaik0721013 how is this possible? Also please fix the Readme to a more up-to-date version. We should probably cherry-pick changes from feature/NAV2020-24129...
